from bayesian_ridge import get_brr_prediction
from elastic_net import get_en_prediction
from lasso_regression import get_lasso_prediction
from linear_regression import get_lr_prediction
from neural_net import get_nn_prediction
from ridge_regression import get_rr_prediction
